HousePEC/HousePEC/urls.py
"""
Definition of urls for HousePEC.
"""

from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.auth import views as auth_views

from pecbyapi import views
from accounts import views as accounts_views

# Uncomment the next two lines to enable the admin:
# from django.contrib import admin
# admin.autodiscover()

# Admin
urlpatterns = [
    url(r'^admin/', admin.site.urls),
]

# Login
urlpatterns += [
    url(r'^signup/$', accounts_views.signup, name='signup')
    ]

urlpatterns += [
    url(r'^logout/$', auth_views.LogoutView.as_view(), name='logout')
    ]

urlpatterns += [
    url(r'^login/$', auth_views.LoginView.as_view(template_name='login.html'), name='login')
    ]

urlpatterns += [
    url(r'^reset/$',
        auth_views.PasswordResetView.as_view(
            template_name='password_reset.html',
            email_template_name='password_reset_email.html',
            subject_template_name='password_reset_subject.txt'
        ),
        name='password_reset'),
    url(r'^reset/done/$',
        auth_views.PasswordResetDoneView.as_view(template_name='password_reset_done.html'),
        name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        auth_views.PasswordResetConfirmView.as_view(template_name='password_reset_confirm.html'),
        name='password_reset_confirm'),
    url(r'^reset/complete/$',
        auth_views.PasswordResetCompleteView.as_view(template_name='password_reset_complete.html'),
        name='password_reset_complete'),    
    ]

urlpatterns += [
    url(r'^settings/password/$', auth_views.PasswordChangeView.as_view(template_name='password_change.html'),
        name='password_change'),
    url(r'^settings/password/done/$', auth_views.PasswordChangeDoneView.as_view(template_name='password_change_done.html'),
        name='password_change_done'),    
    ]

#Home
urlpatterns += [
    url(r'^$', views.home, name='home')
    ]

#HouseBasic
urlpatterns += [
    url(r'^builder/(?P<pk>\d+)/$', views.house_list, name='house_list')
    #url(r'^builder/(?P<pk>\d+)/$', views.HouseListView.as_view(), name='house_list')
    ]

urlpatterns += [
    url(r'^builder/(?P<pk>\d+)/detail/$', views.house_list_detail, name='house_list_detail')    
    ]

urlpatterns += [
    url(r'^builder/(?P<pk>\d+)/house/(?P<house_pk>\d+)/delete/$', views.house_confirm_delete, name='house_confirm_delete')    
    ]

urlpatterns += [
    url(r'^builder/(?P<pk>\d+)/house/(?P<house_pk>\d+)/update/$', views.house_update, name='house_update')    
    #url(r'^builder/(?P<pk>\d+)/house/(?P<house_pk>\d+)/update/$', views.HouseUpdateView.as_view(), name='house_update')    
    ]

urlpatterns += [
    url(r'^builder/(?P<pk>\d+)/house/(?P<house_pk>\d+)/update/detail/$', views.house_update_detail, name='house_update_detail')    
    ]

urlpatterns += [
    url(r'^builder/(?P<pk>\d+)/house/(?P<house_pk>\d+)/copy/$', views.house_copy, name='house_copy')    
    #url(r'^builder/(?P<pk>\d+)/house/(?P<house_pk>\d+)/copy/$', views.HouseCopyView.as_view(), name='house_copy')    
    ]

urlpatterns += [
    url(r'^builder/(?P<pk>\d+)/new/$', views.house_new, name='house_new')
    #url(r'^builder/(?P<pk>\d+)/new/$', views.NewHouseView.as_view(), name='new_house')
    ]

urlpatterns += [
    url(r'^builder/(?P<pk>\d+)/new/detail/$', views.house_new_detail, name='house_new_detail')
    ]


# HaouseSpec
urlpatterns += [
    url(r'^builder/(?P<pk>\d+)/house/(?P<house_pk>\d+)/$', views.spec_list, name='spec_list')    
    #url(r'^builder/(?P<pk>\d+)/house/(?P<house_pk>\d+)/$', views.SpecListView.as_view(), name='spec_list')    
]

urlpatterns += [
    url(r'^builder/(?P<pk>\d+)/house/(?P<house_pk>\d+)/new/$', views.spec_new, name='spec_new')    
]

#urlpatterns += [
#    url(r'^builder/(?P<pk>\d+)/house/(?P<house_pk>\d+)/new/detail/$', views.spec_new_detail, name='spec_new_detail')    
#]

urlpatterns += [
    url(r'^builder/(?P<pk>\d+)/house/(?P<house_pk>\d+)/spec/(?P<spec_pk>\d+)/update/$', views.spec_update, name='spec_update')
]

urlpatterns += [
    url(r'^builder/(?P<pk>\d+)/house/(?P<house_pk>\d+)/spec/(?P<spec_pk>\d+)/copy/$', views.spec_copy, name='spec_copy')
]

urlpatterns += [
    url(r'^builder/(?P<pk>\d+)/house/(?P<house_pk>\d+)/spec/(?P<spec_pk>\d+)/delete/$', views.spec_confirm_delete, name='spec_confirm_delete')
]

urlpatterns += [
    url(r'^builder/(?P<pk>\d+)/house/(?P<house_pk>\d+)/calc/$', views.spec_calc, name='spec_calc')
]

urlpatterns += [
    url(r'^builder/(?P<pk>\d+)/house/(?P<house_pk>\d+)/test/$', views.spec_calc_test, name='spec_calc_test')
]

HousePEC/pecbyapi/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse

import sys
from io import BytesIO
import base64
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np

# Create your models here.


########
######## HouseBuilder
########
class HouseBuilder(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    name = models.CharField('会社名', max_length=200, default='○○工務店', help_text='会社名を入力してください（最大100字）')

    def get_registered_houses(self):
        return HouseBasic.objects.filter(builder=self).count()

    def get_date_joined(self):
        return self.user.date_joined

    def get_builder_name(self):
        return self.name

    def get_absolute_url(self):
        return reverse('house_list', args=[str(self.id)])
    
    def __str__(self):
        return self.user.username


########
######## HouseBasic
########
class HouseBasic(models.Model):
    builder = models.ForeignKey(HouseBuilder, on_delete=models.CASCADE, related_name='houses')
    #builder = models.CharField('会社名', max_length=200, default=self.user.builder)
    name = models.CharField('住宅名', max_length=200, default="○○○○邸", help_text="住宅名を入力してください（最大100字）")
    create_date = models.DateTimeField('住宅登録日時', auto_now_add=True)
    update_date = models.DateTimeField('住宅更新日時', auto_now=True)

    REGION_LIST = (
        ('1', '1地域'),
        ('2', '2地域'),
        ('3', '3地域'),
        ('4', '4地域'),
        ('5', '5地域'),
        ('6', '6地域'),
        ('7', '7地域'),
        ('8', '8地域'),
    )
    region = models.CharField(
        '建設地域', max_length=1, choices=REGION_LIST, blank=False, default="2", 
        help_text="省エネルギー基準地域区分（1～8）を指定してください。")
    
    ANNUALSOLARLEVEL_LIST = (
        ('A1', 'A1区分(年間の日射量が特に少ない地域)'),
        ('A2', 'A2区分(年間の日射量が少ない地域)'),
        ('A3', 'A3区分(年間の日射量が中程度の地域)'),
        ('A4', 'A4区分(年間の日射量が多い地域)'),
        ('A5', 'A5区分(年間の日射量が特に多い地域)'),
    )
    annual_solar_level = models.CharField(
        '日射地域区分', max_length=2, choices=ANNUALSOLARLEVEL_LIST, blank=False, default="A2", 
        help_text="年間日射地域区分（A1～A5）を指定してください。")
    
    HEATSTORAGE_LIST = (
        ('HeatStorage', '利用する'),
        ('None', '利用しない'),
    )
    heat_storage = models.CharField(
        '蓄熱利用', max_length=11, choices=HEATSTORAGE_LIST, blank=False, default="None", 
        help_text="蓄熱利用の有無を指定してください。")

    UNDERFLOORVENTILATION_LIST = (
        ('AlwaysOn', '通年利用する'),
        ('None', '利用しない'),
    )
    under_floor_ventilation = models.CharField(
        '床下経由換気の採用', max_length=8, choices=UNDERFLOORVENTILATION_LIST, blank=False, default="None", 
        help_text="床下換気システム利用の有無を指定してください。")
    under_floor_ventilation_area_rate = models.IntegerField(
        '床下経由換気の面積割合[%]', default=0, blank=False, 
        help_text="外気が経由する床下の面積の割合を％(1～100までの整数)で入力してください。")

    NATURALWIND_LIST = (
        ('0', '自然風を利用しない'),
        ('5', '自然風を利用する（換気回数5回/h相当以上）'),
        ('20', '自然風を利用する（換気回数20回/h相当以上）'),
    )
    ldk_natural_wind = models.CharField(
        '主居室の通風利用', max_length=2, choices=NATURALWIND_LIST, blank=False, default="0", 
        help_text="主居室の自然風による1時間あたりの換気回数を指定してください。")
    oth_natural_wind = models.CharField(
        '他居室の通風利用', max_length=2, choices=NATURALWIND_LIST, blank=False, default="0", 
        help_text="他居室の自然風による1時間あたりの換気回数を指定してください。")

    total_area = models.DecimalField(
        '延床面積[m2]', max_digits=5, decimal_places=2, default=120.08, 
        help_text="延床面積（主居室、他居室、非居室の合計）を、小数点以下2桁まで入力して下さい。")
    ldk_area = models.DecimalField(
        '主居室床面積[m2]', max_digits=5, decimal_places=2, default=29.81, 
        help_text="主居室の床面積を、小数点以下2桁まで入力して下さい。")
    oth_area = models.DecimalField(
        '他居室床面積[m2]', max_digits=5, decimal_places=2, default=51.34, 
        help_text="他居室の床面積を、小数点以下2桁まで入力して下さい。")

    total_envelope_area = models.DecimalField(
        '外皮面積の合計[m2]', max_digits=5, decimal_places=2, default=307.51, 
        help_text="天井、外壁、床、開口部等、すべての外皮面積の合計を、小数点以下2桁まで入力して下さい。")
    ua_value = models.DecimalField(
        'UA値[W/m2・K]', max_digits=3, decimal_places=2, default=0.87, 
        help_text="外皮平均熱貫流率(UA値)を、小数点以下2桁まで入力して下さい。")
    winter_ha_value = models.DecimalField(
        '暖房期ηAH値[-]', max_digits=2, decimal_places=1, default=4.3, 
        help_text="暖房期平均日射熱取得率(ηAH値)を、小数点以下1桁まで入力して下さい。")
    summer_ha_value = models.DecimalField(
        '冷房期ηAC値[-]', max_digits=2, decimal_places=1, default=2.8, 
        help_text="冷房期平均日射熱取得率(ηAC値)を、小数点以下1桁まで入力して下さい。")

    #def get_builder_name(self):
    #    return self.user.builder

    def get_registered_specs(self):
        return HouseSpec.objects.filter(house=self).count()

    def nonldk_area_check(self):
        nonldk_area = self.total_area - (self.ldk_area + self.oth_area)
        if nonldk_area >= 0:
            return True
        return False
    
    def get_last_updated(self):
        return HouseSpec.objects.filter(house=self).order_by('-update_date').first()

    def get_absolute_url(self):
        return reverse('house_list', args=[str(self.id)])

    def __str__(self):
        return self.name


########
######## HouseSpec
########
class HouseSpec(models.Model):
    builder = models.ForeignKey(HouseBuilder, on_delete=models.CASCADE, related_name='specs')
    house = models.ForeignKey(HouseBasic, on_delete=models.CASCADE, related_name='specs')
    def get_registered_specs(self):
        return self.house.get_registered_specs()
    serial_no = models.IntegerField('設備仕様No.', default=0)
    update_date = models.DateTimeField('設備仕様更新日時', auto_now=True)
    calc_done = models.BooleanField('一次エネルギー消費量計算済み', default=False)
    resErrMessage = models.CharField(max_length=255, blank=True, default='')
    resE_T = models.FloatField(blank=True, default=0)
    resE_L = models.FloatField(blank=True, default=0)
    resE_W = models.FloatField(blank=True, default=0)
    resE_V = models.FloatField(blank=True, default=0)
    resE_C = models.FloatField(blank=True, default=0)
    resE_H = models.FloatField(blank=True, default=0)
    resE_M = models.FloatField(blank=True, default=0)
    resE_ST = models.FloatField(blank=True, default=0)
    resE_SL = models.FloatField(blank=True, default=0)
    resE_SW = models.FloatField(blank=True, default=0)
    resE_SV = models.FloatField(blank=True, default=0)
    resE_SC = models.FloatField(blank=True, default=0)
    resE_SH = models.FloatField(blank=True, default=0)
    resE_SM = models.FloatField(blank=True, default=0)
    resReduceByPV = models.FloatField(blank=True, default=0)
    resSellByPV = models.FloatField(blank=True, default=0)
    resGenerateByPV = models.FloatField(blank=True, default=0)
    resGenerateByCG = models.FloatField(blank=True, default=0)

    #暖房方式
    HEATING_SYSTEM_LIST = (
        ('RoomSpaceHeating', '居室部分にのみ暖房設備を設置する（居室のみを暖房する）'),
        ('AllSpaceHeating', '住戸全体（主居室、他居室、非居室の全て）を暖房する設備を設置する'),
        ('NotInstalled', '暖房設備を設置しない'),
        )
    heating_system = models.CharField(
        '暖房方式の選択', max_length=16, choices=HEATING_SYSTEM_LIST, blank=False, default="RoomSpaceHeating", 
        help_text="一般的には「居室部分（主居室と他居室）にのみ暖房設備を設置する」を選択します。「住戸全体を暖房する設備を設置する」を選択すると、暖房設備は「ダクト式セントラル空調機」に設定され、同時に冷房設備も「ダクト式セントラル空調機」に設定されます。「暖房設備を設置しない」を選択した場合、「標準設備機器」を想定して一次エネルギー消費量が計算されます。")
    #LDK_HEATING_TYPE_LIST = (
    #    ('RoomAirConditioningHeating', 'エアコン'),
    #    ('FFHeating', 'FF暖房機'),
    #    ('PanelRadiator', 'パネルラジエーター'),
    #    ('HotWaterFloorHeatingRadiator', '温水床暖房'),
    #    ('FanConvectorRadiator', 'ファンコンベクター'),
    #    ('ElecricFloorHeating', '電気ヒーター床暖房'),
    #    ('ElectricRoomHeaterWithThermalStorage', '電気蓄熱暖房器'),
    #    ('FloorHeatingWithRAC', 'エアコン付温水床暖房機'),
    #    #('ElectricHeatPumpCentralHeating', 'ダクト式セントラル空調機'),
    #    ('OtherHeatingDevice', 'その他の暖房設備機器等'),
    #    #('NotInstalled', '暖房設備機器または放熱器を設置しない'),
    #)
    HEATING_TYPE_LIST = (
        ('RoomAirConditioningHeating', 'エアコン'),
        ('FFHeating', 'FF暖房機'),
        ('PanelRadiator', 'パネルラジエーター'),
        ('HotWaterFloorHeatingRadiator', '温水床暖房'),
        ('FanConvectorRadiator', 'ファンコンベクター'),
        ('ElecricFloorHeating', '電気ヒーター床暖房'),
        ('ElectricRoomHeaterWithThermalStorage', '電気蓄熱暖房器'),
        ('FloorHeatingWithRAC', 'エアコン付温水床暖房機'),
        ('OtherHeatingDevice', 'その他の暖房設備機器等'),
        ('NotInstalled', '暖房設備機器または放熱器を設置しない'),
    )
    ldk_heating_type = models.CharField(
        '主居室の暖房', max_length=36, choices=HEATING_TYPE_LIST, blank=False, default="RoomAirConditioningHeating", 
        help_text="主居室の暖房設備を選択します。「エアコン」を選択すると、主居室の冷房設備も「エアコン」に設定されます。")
    oth_heating_type = models.CharField(
        '他居室の暖房', max_length=36, choices=HEATING_TYPE_LIST, blank=False, default="RoomAirConditioningHeating", 
        help_text="他居室の暖房設備を選択します。「エアコン」を選択すると、他居室の冷房設備も「エアコン」に設定されます。")

    #主居室
    #ルームエアコンディショナー
    AC_HEATING_EFFICIENCY_LIST = (
        ('I', '（い）エアコン'),
        ('RO', '（ろ）エアコン'),
        ('HA', '（は）エアコン'),
        ('None', 'エネルギー消費効率区分を指定しない')
    )
    AC_HEATING_COMPRESSOR_LIST = (
        ('Single', '搭載しない'),
        ('Variable', '搭載する'),
    )
    ldk_ac_heating_efficiency = models.CharField(
        'エネルギー消費効率区分：主居室', max_length=4, choices=AC_HEATING_EFFICIENCY_LIST, default="I", 
        help_text="主居室ルームエアコンディショナー暖房のエネルギー消費効率区分を指定します。")
    ldk_ac_heating_compressor = models.CharField(
        '容量可変型コンプレッサー：主居室', max_length=8, choices=AC_HEATING_COMPRESSOR_LIST, default="Single", 
        help_text="主居室ルームエアコンディショナーの容量可変型コンプレッサー搭載の有無を指定します。")
    #FF暖房機
    ldk_ff_saving_input = models.BooleanField(
        '主居室FF暖房のエネルギー消費効率の入力', default=True, 
        help_text="主居室FF暖房のエネルギー消費効率を入力する場合はチェックして下さい。")
    ldk_ff_heating_efficiency = models.DecimalField(
        'FF暖房効率[%]：主居室', max_digits=3, decimal_places=1, default=86.0, 
        help_text="主居室FF暖房機の定格能力におけるエネルギー消費効率を、小数点以下1桁まで指定します。")
    #パネルラジエーター
    #温水床暖房

HousePEC/templates/house_confirm_delete.html
{% extends 'base.html' %}

{% block title %}
  {{ house.builder.name }} - {{ block.super }}
{% endblock %}

{% block breadcrumb %}
  <li class="breadcrumb-item"><a href="{% url 'home' %}">一次エネルギー消費量計算</a></li>
  <li class="breadcrumb-item"><a href="{% url 'house_list' house.builder.pk %}">{{ house.builder.name }}</a></li>
  {#<li class="breadcrumb-item"><a href="{% url 'spec_list' house.builder.pk house.pk %}">{{ house.name }}</a></li>#}
  <li class="breadcrumb-item active">登録住宅の削除</li>
{% endblock %}

{% block content %}

<p>
    <a href="{% url 'house_list' house.builder.pk %}">住宅リスト一覧に戻る</a>
</p>

<p class="text-danger">
    住宅「{{ house.name }}」は、以下の内容で登録されています。<br />
    この住宅を削除するには、ページ下部の「削除」をクリックして下さい。<br />
    この住宅を削除すると、付随して登録されている性能・設備仕様も同時に削除されるので、ご注意ください。
</p>

    <div class="card mb-2">
        <div class="card-header">
            住宅「{{ house.name }}」の登録内容
        </div>
      <div class="card-body">

        <table class="table table-sm">
            <thead class="thead-light">
                <tr>
                    <th>UA値[W/m2・K]</th>
                    <th colspan="2">ηH値[-]</th>
                    <th>外皮面積[m2]</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>{{ house.ua_value }}</td>
                    <td>暖房期：{{ house.winter_ha_value }}</td>
                    <td>冷房期：{{ house.summer_ha_value }}</td>
                    <td>{{ house.total_envelope_area }}</td>
                </tr>
            </tbody>
        </table>

        <table class="table table-sm">
            <thead class="thead-light">
                <tr>
                    <th colspan="3">床面積[m2]</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>延床：{{ house.total_area }}</td>
                    <td>主居室：{{ house.ldk_area }}</td>
                    <td>他居室：{{ house.oth_area }}</td>
                </tr>
            </tbody>
        </table>

        <table class="table table-sm">
            <thead class="thead-light">
                <tr>
                    <th>建設地域</th>
                    <th>日射区分</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>{{ house.get_region_display }}</td>
                    <td>{{ house.get_annual_solar_level_display }}</td>
                </tr>
            </tbody>
        </table>

        <table class="table table-sm">
            <thead class="thead-light">
                <tr>
                    <th>住宅の登録日時</th>
                    <th>住宅の更新日時</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>{{ house.create_date }}</td>
                    <td>{{ house.update_date }}</td>
                </tr>
            </tbody>
        </table>

        <table class="table table-sm">
            <thead class="thead-light">
                <tr>
                    <th>設備仕様登録数</th>
                    <th>設備仕様の最終更新日時</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>{{ house.get_registered_specs }}</td>
                    <td>{{ house.get_last_updated.update_date }}</td>
                </tr>
            </tbody>
        </table>

        <div class="card mb-2">
            <div class="card-header">
                詳細設定項目
            </div>
            <div class="card-body">
                <table class="table table-sm">
                    <thead class="thead-light">
                        <tr>
                            <th>蓄熱利用</th>
                            <th>床下経由換気</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td>{{ house.get_heat_storage_display }}</td>
                            {% if house.under_floor_ventilation == 'AlwaysOn' %}
                                <td>{{ house.get_under_floor_ventilation_display }}（面積割合：{{ house.under_floor_ventilation_area_rate }}%）</td>
                            {% else %}
                                <td>{{ house.get_under_floor_ventilation_display }}</td>
                            {% endif %}
                        </tr>
                    </tbody>
                </table>

                <table class="table table-sm">
                    <thead class="thead-light">
                        <tr>
                            <th colspan="2">通風利用</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td>主居室：{{ house.get_ldk_natural_wind_display }}</td>
                            <td>他居室：{{ house.get_oth_natural_wind_display }}</td>
                        </tr>
                    </tbody>
                </table>

            </div>
        </div>
      </div>
    </div>

<p class="text-danger">この操作は取り消すことができません。内容を確認してから「削除」をクリックしてください。</p>

  <form method="post">
    {% csrf_token %}
      {% include 'includes/form.html' %}
      
    <button type="submit" class="btn btn-danger">削除</button>
  </form>

{% endblock %}

HousePEC/templates/house_list.html
{% extends 'base.html' %}

{% block breadcrumb %}
  <li class="breadcrumb-item"><a href="{% url 'home' %}">一次エネルギー消費量計算</a></li>
  <li class="breadcrumb-item active">登録住宅リスト：{{ builder.name }}</li>
  <li class="breadcrumb-item active">{{ house.all.count }}棟の登録があります</li>
{% endblock %}

{% block content %}

  <div class="mb-4">
    <a href="{% url 'house_new' builder.pk %}" class="btn btn-primary" data-toggle="tooltip" data-placement="bottom" title="クリックすると住宅の新規作成画面に移ります">
     住宅の新規作成
    </a>
      （最大10棟まで登録できます）
  </div>

{% if house.all.count %}

    <p>
        各住宅の設備仕様の追加・変更を行う場合は、下のリストの中の、それぞれの住宅名をクリックして下さい。<br />
        各住宅の住宅名や建設地域、床面積等の変更を行う場合は、「変更」をクリックして下さい。<br />
        各住宅の複製を作成する場合は、「複製」をクリックして下さい。複製された住宅は、リストの最後に追加されます。<br />
        登録された住宅を削除する場合は、「削除」をクリックして下さい。<br />
    <small>
        *蓄熱の利用や床下経由換気の採用、通風利用等の詳細設定も含めてリスト表示する場合は、
        <a href="{% url 'house_list_detail' builder.pk %} ">こちら</a>をクリックしてください。
    </small>
    </p>

{% for i in house.all %}
    <div class="card mb-2">
        <div class="card-header">
            No.{{ forloop.counter }}: 
        </div>
      <div class="card-body">

        <div class="row mb-2">
            <div class="col-8">
                <a href="{% url 'spec_list' builder.pk i.pk %}" class="btn btn-primary btn-sm" data-toggle="tooltip" data-placement="bottom" title="性能・設備仕様の追加・変更を行います">
                {{ i.name }}
                </a>
            </div>
            <div class="col-4 text-right">
                <div>
                    <a href="{% url 'house_update' builder.pk i.pk %}" class="btn btn-success btn-sm" data-toggle="tooltip" data-placement="bottom" title="住宅名や建設地域、床面積等の変更を行います">変更</a>
                    <a href="{% url 'house_copy' builder.pk i.pk %}" class="btn btn-warning btn-sm" data-toggle="tooltip" data-placement="bottom" title="複製された住宅はリストの最後に追加されます">複製</a>
                    <a href="{% url 'house_confirm_delete' builder.pk i.pk %}" class="btn btn-danger btn-sm" data-toggle="tooltip" data-placement="bottom" title="登録された住宅が削除されます">削除</a>
                </div>
            </div>
        </div>

        <table class="table table-sm">
            <thead class="thead-light">
                <tr>
                    <th>UA値[W/m2・K]</th>
                    <th colspan="2">ηH値[-]</th>
                    <th>外皮面積[m2]</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>{{ i.ua_value }}</td>
                    <td>暖房期：{{ i.winter_ha_value }}</td>
                    <td>冷房期：{{ i.summer_ha_value }}</td>
                    <td>{{ i.total_envelope_area }}</td>
                </tr>
            </tbody>
        </table>

        <table class="table table-sm">
            <thead class="thead-light">
                <tr>
                    <th colspan="3">床面積[m2]</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>延床：{{ i.total_area }}</td>
                    <td>主居室：{{ i.ldk_area }}</td>
                    <td>他居室：{{ i.oth_area }}</td>
                </tr>
            </tbody>
        </table>

        <table class="table table-sm">
            <thead class="thead-light">
                <tr>
                    <th>建設地域</th>
                    <th>日射区分</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>{{ i.get_region_display }}</td>
                    <td>{{ i.get_annual_solar_level_display }}</td>
                </tr>
            </tbody>
        </table>

        <table class="table table-sm">
            <thead class="thead-light">
                <tr>
                    <th>住宅の登録日時</th>
                    <th>住宅の更新日時</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>{{ i.create_date }}</td>
                    <td>{{ i.update_date }}</td>
                </tr>
            </tbody>
        </table>

        <table class="table table-sm">
            <thead class="thead-light">
                <tr>
                    <th>設備仕様登録数</th>
                    <th>設備仕様の最終更新日時</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>{{ i.get_registered_specs }}</td>
                    <td>{{ i.get_last_updated.update_date }}</td>
                </tr>
            </tbody>
        </table>

      </div>
    </div>

{% endfor %}

{% else %}

    <p>登録されている住宅はありません。</p>

{% endif %}

{% endblock %}

HousePEC/templates/password_change.html
{% extends 'base.html' %}

{% block title %}Change password{% endblock %}

{% block breadcrumb %}
  <li class="breadcrumb-item active">Change password</li>
{% endblock %}

{% block content %}
  <div class="row">
    <div class="col-lg-6 col-md-8 col-sm-10">
      <form method="post" novalidate>
        {% csrf_token %}
        {% include 'includes/form.html' %}
        <button type="submit" class="btn btn-success">Change password</button>
      </form>
    </div>
  </div>
{% endblock %}